from plaid.model_utils import ApiTypeError as ApiTypeError, ModelComposed as ModelComposed, ModelNormal as ModelNormal, ModelSimple as ModelSimple, cached_property as cached_property, change_keys_js_to_python as change_keys_js_to_python, convert_js_args_to_python_args as convert_js_args_to_python_args, file_type as file_type, none_type as none_type, validate_get_composed_info as validate_get_composed_info
from typing import Any

def lazy_import() -> None: ...

class BankTransferEvent(ModelNormal):
    allowed_values: Any = ...
    validations: Any = ...
    attribute_map: Any = ...
    required_properties: Any = ...
    event_id: Any = ...
    timestamp: Any = ...
    event_type: Any = ...
    account_id: Any = ...
    bank_transfer_id: Any = ...
    bank_transfer_type: Any = ...
    bank_transfer_amount: Any = ...
    bank_transfer_iso_currency_code: Any = ...
    failure_reason: Any = ...
    direction: Any = ...
    receiver_details: Any = ...
    def __init__(self, event_id: Any, timestamp: Any, event_type: Any, account_id: Any, bank_transfer_id: Any, bank_transfer_type: Any, bank_transfer_amount: Any, bank_transfer_iso_currency_code: Any, failure_reason: Any, direction: Any, receiver_details: Any, *args: Any, **kwargs: Any) -> None: ...
