from plaid.model_utils import ApiTypeError as ApiTypeError, ModelComposed as ModelComposed, ModelNormal as ModelNormal, ModelSimple as ModelSimple, cached_property as cached_property, change_keys_js_to_python as change_keys_js_to_python, convert_js_args_to_python_args as convert_js_args_to_python_args, file_type as file_type, none_type as none_type, validate_get_composed_info as validate_get_composed_info
from typing import Any

class Security(ModelNormal):
    allowed_values: Any = ...
    validations: Any = ...
    attribute_map: Any = ...
    required_properties: Any = ...
    security_id: Any = ...
    isin: Any = ...
    cusip: Any = ...
    sedol: Any = ...
    institution_security_id: Any = ...
    institution_id: Any = ...
    proxy_security_id: Any = ...
    name: Any = ...
    ticker_symbol: Any = ...
    is_cash_equivalent: Any = ...
    type: Any = ...
    close_price: Any = ...
    close_price_as_of: Any = ...
    iso_currency_code: Any = ...
    unofficial_currency_code: Any = ...
    def __init__(self, security_id: Any, isin: Any, cusip: Any, sedol: Any, institution_security_id: Any, institution_id: Any, proxy_security_id: Any, name: Any, ticker_symbol: Any, is_cash_equivalent: Any, type: Any, close_price: Any, close_price_as_of: Any, iso_currency_code: Any, unofficial_currency_code: Any, *args: Any, **kwargs: Any) -> None: ...
