from plaid.api_client import ApiClient as ApiClient
from plaid.model.accounts_balance_get_request import AccountsBalanceGetRequest as AccountsBalanceGetRequest
from plaid.model.accounts_get_request import AccountsGetRequest as AccountsGetRequest
from plaid.model.accounts_get_response import AccountsGetResponse as AccountsGetResponse
from plaid.model.application_get_request import ApplicationGetRequest as ApplicationGetRequest
from plaid.model.application_get_response import ApplicationGetResponse as ApplicationGetResponse
from plaid.model.asset_report_audit_copy_create_request import AssetReportAuditCopyCreateRequest as AssetReportAuditCopyCreateRequest
from plaid.model.asset_report_audit_copy_create_response import AssetReportAuditCopyCreateResponse as AssetReportAuditCopyCreateResponse
from plaid.model.asset_report_audit_copy_get_request import AssetReportAuditCopyGetRequest as AssetReportAuditCopyGetRequest
from plaid.model.asset_report_audit_copy_remove_request import AssetReportAuditCopyRemoveRequest as AssetReportAuditCopyRemoveRequest
from plaid.model.asset_report_audit_copy_remove_response import AssetReportAuditCopyRemoveResponse as AssetReportAuditCopyRemoveResponse
from plaid.model.asset_report_create_request import AssetReportCreateRequest as AssetReportCreateRequest
from plaid.model.asset_report_create_response import AssetReportCreateResponse as AssetReportCreateResponse
from plaid.model.asset_report_filter_request import AssetReportFilterRequest as AssetReportFilterRequest
from plaid.model.asset_report_filter_response import AssetReportFilterResponse as AssetReportFilterResponse
from plaid.model.asset_report_get_request import AssetReportGetRequest as AssetReportGetRequest
from plaid.model.asset_report_get_response import AssetReportGetResponse as AssetReportGetResponse
from plaid.model.asset_report_pdf_get_request import AssetReportPDFGetRequest as AssetReportPDFGetRequest
from plaid.model.asset_report_refresh_request import AssetReportRefreshRequest as AssetReportRefreshRequest
from plaid.model.asset_report_refresh_response import AssetReportRefreshResponse as AssetReportRefreshResponse
from plaid.model.asset_report_remove_request import AssetReportRemoveRequest as AssetReportRemoveRequest
from plaid.model.asset_report_remove_response import AssetReportRemoveResponse as AssetReportRemoveResponse
from plaid.model.auth_get_request import AuthGetRequest as AuthGetRequest
from plaid.model.auth_get_response import AuthGetResponse as AuthGetResponse
from plaid.model.bank_transfer_balance_get_request import BankTransferBalanceGetRequest as BankTransferBalanceGetRequest
from plaid.model.bank_transfer_balance_get_response import BankTransferBalanceGetResponse as BankTransferBalanceGetResponse
from plaid.model.bank_transfer_cancel_request import BankTransferCancelRequest as BankTransferCancelRequest
from plaid.model.bank_transfer_cancel_response import BankTransferCancelResponse as BankTransferCancelResponse
from plaid.model.bank_transfer_create_request import BankTransferCreateRequest as BankTransferCreateRequest
from plaid.model.bank_transfer_create_response import BankTransferCreateResponse as BankTransferCreateResponse
from plaid.model.bank_transfer_event_list_request import BankTransferEventListRequest as BankTransferEventListRequest
from plaid.model.bank_transfer_event_list_response import BankTransferEventListResponse as BankTransferEventListResponse
from plaid.model.bank_transfer_event_sync_request import BankTransferEventSyncRequest as BankTransferEventSyncRequest
from plaid.model.bank_transfer_event_sync_response import BankTransferEventSyncResponse as BankTransferEventSyncResponse
from plaid.model.bank_transfer_get_request import BankTransferGetRequest as BankTransferGetRequest
from plaid.model.bank_transfer_get_response import BankTransferGetResponse as BankTransferGetResponse
from plaid.model.bank_transfer_list_request import BankTransferListRequest as BankTransferListRequest
from plaid.model.bank_transfer_list_response import BankTransferListResponse as BankTransferListResponse
from plaid.model.bank_transfer_migrate_account_request import BankTransferMigrateAccountRequest as BankTransferMigrateAccountRequest
from plaid.model.bank_transfer_migrate_account_response import BankTransferMigrateAccountResponse as BankTransferMigrateAccountResponse
from plaid.model.categories_get_response import CategoriesGetResponse as CategoriesGetResponse
from plaid.model.deposit_switch_alt_create_request import DepositSwitchAltCreateRequest as DepositSwitchAltCreateRequest
from plaid.model.deposit_switch_alt_create_response import DepositSwitchAltCreateResponse as DepositSwitchAltCreateResponse
from plaid.model.deposit_switch_create_request import DepositSwitchCreateRequest as DepositSwitchCreateRequest
from plaid.model.deposit_switch_create_response import DepositSwitchCreateResponse as DepositSwitchCreateResponse
from plaid.model.deposit_switch_get_request import DepositSwitchGetRequest as DepositSwitchGetRequest
from plaid.model.deposit_switch_get_response import DepositSwitchGetResponse as DepositSwitchGetResponse
from plaid.model.deposit_switch_token_create_request import DepositSwitchTokenCreateRequest as DepositSwitchTokenCreateRequest
from plaid.model.deposit_switch_token_create_response import DepositSwitchTokenCreateResponse as DepositSwitchTokenCreateResponse
from plaid.model.employers_search_request import EmployersSearchRequest as EmployersSearchRequest
from plaid.model.employers_search_response import EmployersSearchResponse as EmployersSearchResponse
from plaid.model.error import Error as Error
from plaid.model.identity_get_request import IdentityGetRequest as IdentityGetRequest
from plaid.model.identity_get_response import IdentityGetResponse as IdentityGetResponse
from plaid.model.income_verification_create_request import IncomeVerificationCreateRequest as IncomeVerificationCreateRequest
from plaid.model.income_verification_create_response import IncomeVerificationCreateResponse as IncomeVerificationCreateResponse
from plaid.model.income_verification_documents_download_request import IncomeVerificationDocumentsDownloadRequest as IncomeVerificationDocumentsDownloadRequest
from plaid.model.income_verification_paystub_get_request import IncomeVerificationPaystubGetRequest as IncomeVerificationPaystubGetRequest
from plaid.model.income_verification_paystub_get_response import IncomeVerificationPaystubGetResponse as IncomeVerificationPaystubGetResponse
from plaid.model.income_verification_summary_get_request import IncomeVerificationSummaryGetRequest as IncomeVerificationSummaryGetRequest
from plaid.model.income_verification_summary_get_response import IncomeVerificationSummaryGetResponse as IncomeVerificationSummaryGetResponse
from plaid.model.institutions_get_by_id_request import InstitutionsGetByIdRequest as InstitutionsGetByIdRequest
from plaid.model.institutions_get_by_id_response import InstitutionsGetByIdResponse as InstitutionsGetByIdResponse
from plaid.model.institutions_get_request import InstitutionsGetRequest as InstitutionsGetRequest
from plaid.model.institutions_get_response import InstitutionsGetResponse as InstitutionsGetResponse
from plaid.model.institutions_search_request import InstitutionsSearchRequest as InstitutionsSearchRequest
from plaid.model.institutions_search_response import InstitutionsSearchResponse as InstitutionsSearchResponse
from plaid.model.investments_holdings_get_request import InvestmentsHoldingsGetRequest as InvestmentsHoldingsGetRequest
from plaid.model.investments_holdings_get_response import InvestmentsHoldingsGetResponse as InvestmentsHoldingsGetResponse
from plaid.model.investments_transactions_get_request import InvestmentsTransactionsGetRequest as InvestmentsTransactionsGetRequest
from plaid.model.investments_transactions_get_response import InvestmentsTransactionsGetResponse as InvestmentsTransactionsGetResponse
from plaid.model.item_access_token_invalidate_request import ItemAccessTokenInvalidateRequest as ItemAccessTokenInvalidateRequest
from plaid.model.item_access_token_invalidate_response import ItemAccessTokenInvalidateResponse as ItemAccessTokenInvalidateResponse
from plaid.model.item_get_request import ItemGetRequest as ItemGetRequest
from plaid.model.item_get_response import ItemGetResponse as ItemGetResponse
from plaid.model.item_import_request import ItemImportRequest as ItemImportRequest
from plaid.model.item_import_response import ItemImportResponse as ItemImportResponse
from plaid.model.item_public_token_create_request import ItemPublicTokenCreateRequest as ItemPublicTokenCreateRequest
from plaid.model.item_public_token_create_response import ItemPublicTokenCreateResponse as ItemPublicTokenCreateResponse
from plaid.model.item_public_token_exchange_request import ItemPublicTokenExchangeRequest as ItemPublicTokenExchangeRequest
from plaid.model.item_public_token_exchange_response import ItemPublicTokenExchangeResponse as ItemPublicTokenExchangeResponse
from plaid.model.item_remove_request import ItemRemoveRequest as ItemRemoveRequest
from plaid.model.item_remove_response import ItemRemoveResponse as ItemRemoveResponse
from plaid.model.item_webhook_update_request import ItemWebhookUpdateRequest as ItemWebhookUpdateRequest
from plaid.model.item_webhook_update_response import ItemWebhookUpdateResponse as ItemWebhookUpdateResponse
from plaid.model.liabilities_get_request import LiabilitiesGetRequest as LiabilitiesGetRequest
from plaid.model.liabilities_get_response import LiabilitiesGetResponse as LiabilitiesGetResponse
from plaid.model.link_token_create_request import LinkTokenCreateRequest as LinkTokenCreateRequest
from plaid.model.link_token_create_response import LinkTokenCreateResponse as LinkTokenCreateResponse
from plaid.model.link_token_get_request import LinkTokenGetRequest as LinkTokenGetRequest
from plaid.model.link_token_get_response import LinkTokenGetResponse as LinkTokenGetResponse
from plaid.model.payment_initiation_payment_create_request import PaymentInitiationPaymentCreateRequest as PaymentInitiationPaymentCreateRequest
from plaid.model.payment_initiation_payment_create_response import PaymentInitiationPaymentCreateResponse as PaymentInitiationPaymentCreateResponse
from plaid.model.payment_initiation_payment_get_request import PaymentInitiationPaymentGetRequest as PaymentInitiationPaymentGetRequest
from plaid.model.payment_initiation_payment_get_response import PaymentInitiationPaymentGetResponse as PaymentInitiationPaymentGetResponse
from plaid.model.payment_initiation_payment_list_request import PaymentInitiationPaymentListRequest as PaymentInitiationPaymentListRequest
from plaid.model.payment_initiation_payment_list_response import PaymentInitiationPaymentListResponse as PaymentInitiationPaymentListResponse
from plaid.model.payment_initiation_payment_token_create_request import PaymentInitiationPaymentTokenCreateRequest as PaymentInitiationPaymentTokenCreateRequest
from plaid.model.payment_initiation_payment_token_create_response import PaymentInitiationPaymentTokenCreateResponse as PaymentInitiationPaymentTokenCreateResponse
from plaid.model.payment_initiation_recipient_create_request import PaymentInitiationRecipientCreateRequest as PaymentInitiationRecipientCreateRequest
from plaid.model.payment_initiation_recipient_create_response import PaymentInitiationRecipientCreateResponse as PaymentInitiationRecipientCreateResponse
from plaid.model.payment_initiation_recipient_get_request import PaymentInitiationRecipientGetRequest as PaymentInitiationRecipientGetRequest
from plaid.model.payment_initiation_recipient_get_response import PaymentInitiationRecipientGetResponse as PaymentInitiationRecipientGetResponse
from plaid.model.payment_initiation_recipient_list_request import PaymentInitiationRecipientListRequest as PaymentInitiationRecipientListRequest
from plaid.model.payment_initiation_recipient_list_response import PaymentInitiationRecipientListResponse as PaymentInitiationRecipientListResponse
from plaid.model.processor_apex_processor_token_create_request import ProcessorApexProcessorTokenCreateRequest as ProcessorApexProcessorTokenCreateRequest
from plaid.model.processor_auth_get_request import ProcessorAuthGetRequest as ProcessorAuthGetRequest
from plaid.model.processor_auth_get_response import ProcessorAuthGetResponse as ProcessorAuthGetResponse
from plaid.model.processor_balance_get_request import ProcessorBalanceGetRequest as ProcessorBalanceGetRequest
from plaid.model.processor_balance_get_response import ProcessorBalanceGetResponse as ProcessorBalanceGetResponse
from plaid.model.processor_identity_get_request import ProcessorIdentityGetRequest as ProcessorIdentityGetRequest
from plaid.model.processor_identity_get_response import ProcessorIdentityGetResponse as ProcessorIdentityGetResponse
from plaid.model.processor_stripe_bank_account_token_create_request import ProcessorStripeBankAccountTokenCreateRequest as ProcessorStripeBankAccountTokenCreateRequest
from plaid.model.processor_stripe_bank_account_token_create_response import ProcessorStripeBankAccountTokenCreateResponse as ProcessorStripeBankAccountTokenCreateResponse
from plaid.model.processor_token_create_request import ProcessorTokenCreateRequest as ProcessorTokenCreateRequest
from plaid.model.processor_token_create_response import ProcessorTokenCreateResponse as ProcessorTokenCreateResponse
from plaid.model.sandbox_bank_transfer_fire_webhook_request import SandboxBankTransferFireWebhookRequest as SandboxBankTransferFireWebhookRequest
from plaid.model.sandbox_bank_transfer_fire_webhook_response import SandboxBankTransferFireWebhookResponse as SandboxBankTransferFireWebhookResponse
from plaid.model.sandbox_bank_transfer_simulate_request import SandboxBankTransferSimulateRequest as SandboxBankTransferSimulateRequest
from plaid.model.sandbox_bank_transfer_simulate_response import SandboxBankTransferSimulateResponse as SandboxBankTransferSimulateResponse
from plaid.model.sandbox_item_fire_webhook_request import SandboxItemFireWebhookRequest as SandboxItemFireWebhookRequest
from plaid.model.sandbox_item_fire_webhook_response import SandboxItemFireWebhookResponse as SandboxItemFireWebhookResponse
from plaid.model.sandbox_item_reset_login_request import SandboxItemResetLoginRequest as SandboxItemResetLoginRequest
from plaid.model.sandbox_item_reset_login_response import SandboxItemResetLoginResponse as SandboxItemResetLoginResponse
from plaid.model.sandbox_item_set_verification_status_request import SandboxItemSetVerificationStatusRequest as SandboxItemSetVerificationStatusRequest
from plaid.model.sandbox_item_set_verification_status_response import SandboxItemSetVerificationStatusResponse as SandboxItemSetVerificationStatusResponse
from plaid.model.sandbox_processor_token_create_request import SandboxProcessorTokenCreateRequest as SandboxProcessorTokenCreateRequest
from plaid.model.sandbox_processor_token_create_response import SandboxProcessorTokenCreateResponse as SandboxProcessorTokenCreateResponse
from plaid.model.sandbox_public_token_create_request import SandboxPublicTokenCreateRequest as SandboxPublicTokenCreateRequest
from plaid.model.sandbox_public_token_create_response import SandboxPublicTokenCreateResponse as SandboxPublicTokenCreateResponse
from plaid.model.transactions_get_request import TransactionsGetRequest as TransactionsGetRequest
from plaid.model.transactions_get_response import TransactionsGetResponse as TransactionsGetResponse
from plaid.model.transactions_refresh_request import TransactionsRefreshRequest as TransactionsRefreshRequest
from plaid.model.transactions_refresh_response import TransactionsRefreshResponse as TransactionsRefreshResponse
from plaid.model.webhook_verification_key_get_request import WebhookVerificationKeyGetRequest as WebhookVerificationKeyGetRequest
from plaid.model.webhook_verification_key_get_response import WebhookVerificationKeyGetResponse as WebhookVerificationKeyGetResponse
from plaid.model_utils import check_allowed_values as check_allowed_values, check_validations as check_validations, file_type as file_type, none_type as none_type, validate_and_convert_types as validate_and_convert_types
from typing import Any, Dict, Optional

class PlaidApi:
    api_client: Any = ...
    def accounts_balance_get(self, request: AccountsBalanceGetRequest) -> AccountsGetResponse: ...
    def accounts_get(self, request: AccountsGetRequest) -> AccountsGetResponse: ...
    def application_get(self, request: ApplicationGetRequest) -> ApplicationGetResponse: ...
    def asset_report_audit_copy_create(self, request: AssetReportAuditCopyCreateRequest) -> AssetReportAuditCopyCreateResponse: ...
    def asset_report_audit_copy_get(self, request: AssetReportAuditCopyGetRequest) -> AssetReportGetResponse: ...
    def asset_report_audit_copy_remove(self, request: AssetReportAuditCopyRemoveRequest) -> AssetReportAuditCopyRemoveResponse: ...
    def asset_report_create(self, request: AssetReportCreateRequest) -> AssetReportCreateResponse: ...
    def asset_report_filter(self, request: AssetReportFilterRequest) -> AssetReportFilterResponse: ...
    def asset_report_get(self, request: AssetReportGetRequest) -> AssetReportGetResponse: ...
    def asset_report_pdf_get(self, request: AssetReportPDFGetRequest) -> file_type: ...
    def asset_report_refresh(self, request: AssetReportRefreshRequest) -> AssetReportRefreshResponse: ...
    def asset_report_remove(self, request: AssetReportRemoveRequest) -> AssetReportRemoveResponse: ...
    def auth_get(self, request: AuthGetRequest) -> AuthGetResponse: ...
    def bank_transfer_balance_get(self, request: BankTransferBalanceGetRequest) -> BankTransferBalanceGetResponse: ...
    def bank_transfer_cancel(self, request: BankTransferCancelRequest) -> BankTransferCancelResponse: ...
    def bank_transfer_create(self, request: BankTransferCreateRequest) -> BankTransferCreateResponse: ...
    def bank_transfer_event_list(self, request: BankTransferEventListRequest) -> BankTransferEventListResponse: ...
    def bank_transfer_event_sync(self, request: BankTransferEventSyncRequest) -> BankTransferEventSyncResponse: ...
    def bank_transfer_get(self, request: BankTransferGetRequest) -> BankTransferGetResponse: ...
    def bank_transfer_list(self, request: BankTransferListRequest) -> BankTransferListResponse: ...
    def bank_transfer_migrate_account(self, request: BankTransferMigrateAccountRequest) -> BankTransferMigrateAccountResponse: ...
    def categories_get(self, body: Dict[str, Any]) -> CategoriesGetResponse: ...
    def create_payment_token(self, request: PaymentInitiationPaymentTokenCreateRequest) -> PaymentInitiationPaymentTokenCreateResponse: ...
    def deposit_switch_alt_create(self, request: DepositSwitchAltCreateRequest) -> DepositSwitchAltCreateResponse: ...
    def deposit_switch_create(self, request: DepositSwitchCreateRequest) -> DepositSwitchCreateResponse: ...
    def deposit_switch_get(self, request: DepositSwitchGetRequest) -> DepositSwitchGetResponse: ...
    def deposit_switch_token_create(self, request: DepositSwitchTokenCreateRequest) -> DepositSwitchTokenCreateResponse: ...
    def employers_search(self, request: EmployersSearchRequest) -> EmployersSearchResponse: ...
    def identity_get(self, request: IdentityGetRequest) -> IdentityGetResponse: ...
    def income_verification_create(self, request: IncomeVerificationCreateRequest) -> IncomeVerificationCreateResponse: ...
    def income_verification_documents_download(self, request: IncomeVerificationDocumentsDownloadRequest) -> file_type: ...
    def income_verification_paystub_get(self, request: IncomeVerificationPaystubGetRequest) -> IncomeVerificationPaystubGetResponse: ...
    def income_verification_summary_get(self, request: IncomeVerificationSummaryGetRequest) -> IncomeVerificationSummaryGetResponse: ...
    def institutions_get(self, request: InstitutionsGetRequest) -> InstitutionsGetResponse: ...
    def institutions_get_by_id(self, request: InstitutionsGetByIdRequest) -> InstitutionsGetByIdResponse: ...
    def institutions_search(self, request: InstitutionsSearchRequest) -> InstitutionsSearchResponse: ...
    def investments_holdings_get(self, request: InvestmentsHoldingsGetRequest) -> InvestmentsHoldingsGetResponse: ...
    def investments_transactions_get(self, request: InvestmentsTransactionsGetRequest) -> InvestmentsTransactionsGetResponse: ...
    def item_access_token_invalidate(self, request: ItemAccessTokenInvalidateRequest) -> ItemAccessTokenInvalidateResponse: ...
    def item_create_public_token(self, request: ItemPublicTokenCreateRequest) -> ItemPublicTokenCreateResponse: ...
    def item_get(self, request: ItemGetRequest) -> ItemGetResponse: ...
    def item_import(self, request: ItemImportRequest) -> ItemImportResponse: ...
    def item_public_token_exchange(self, request: ItemPublicTokenExchangeRequest) -> ItemPublicTokenExchangeResponse: ...
    def item_remove(self, request: ItemRemoveRequest) -> ItemRemoveResponse: ...
    def item_webhook_update(self, request: ItemWebhookUpdateRequest) -> ItemWebhookUpdateResponse: ...
    def liabilities_get(self, request: LiabilitiesGetRequest) -> LiabilitiesGetResponse: ...
    def link_token_create(self, request: LinkTokenCreateRequest) -> LinkTokenCreateResponse: ...
    def link_token_get(self, request: LinkTokenGetRequest) -> LinkTokenGetResponse: ...
    def payment_initiation_payment_create(self, request: PaymentInitiationPaymentCreateRequest) -> PaymentInitiationPaymentCreateResponse: ...
    def payment_initiation_payment_get(self, request: PaymentInitiationPaymentGetRequest) -> PaymentInitiationPaymentGetResponse: ...
    def payment_initiation_payment_list(self, request: PaymentInitiationPaymentListRequest) -> PaymentInitiationPaymentListResponse: ...
    def payment_initiation_recipient_create(self, request: PaymentInitiationRecipientCreateRequest) -> PaymentInitiationRecipientCreateResponse: ...
    def payment_initiation_recipient_get(self, request: PaymentInitiationRecipientGetRequest) -> PaymentInitiationRecipientGetResponse: ...
    def payment_initiation_recipient_list(self, request: PaymentInitiationRecipientListRequest) -> PaymentInitiationRecipientListResponse: ...
    def processor_apex_processor_token_create(self, request: ProcessorApexProcessorTokenCreateRequest) -> ProcessorTokenCreateResponse: ...
    def processor_auth_get(self, request: ProcessorAuthGetRequest) -> ProcessorAuthGetResponse: ...
    def processor_balance_get(self, request: ProcessorBalanceGetRequest) -> ProcessorBalanceGetResponse: ...
    def processor_identity_get(self, request: ProcessorIdentityGetRequest) -> ProcessorIdentityGetResponse: ...
    def processor_stripe_bank_account_token_create(self, request: ProcessorStripeBankAccountTokenCreateRequest) -> ProcessorStripeBankAccountTokenCreateResponse: ...
    def processor_token_create(self, request: ProcessorTokenCreateRequest) -> ProcessorTokenCreateResponse: ...
    def sandbox_bank_transfer_fire_webhook(self, request: SandboxBankTransferFireWebhookRequest) -> SandboxBankTransferFireWebhookResponse: ...
    def sandbox_bank_transfer_simulate(self, request: SandboxBankTransferSimulateRequest) -> SandboxBankTransferSimulateResponse: ...
    def sandbox_item_fire_webhook(self, request: SandboxItemFireWebhookRequest) -> SandboxItemFireWebhookResponse: ...
    def sandbox_item_reset_login(self, request: SandboxItemResetLoginRequest) -> SandboxItemResetLoginResponse: ...
    def sandbox_item_set_verification_status(self, request: SandboxItemSetVerificationStatusRequest) -> SandboxItemSetVerificationStatusResponse: ...
    def sandbox_processor_token_create(self, request: SandboxProcessorTokenCreateRequest) -> SandboxProcessorTokenCreateResponse: ...
    def sandbox_public_token_create(self, request: SandboxPublicTokenCreateRequest) -> SandboxPublicTokenCreateResponse: ...
    def transactions_get(self, request: TransactionsGetRequest) -> TransactionsGetResponse: ...
    def transactions_refresh(self, request: TransactionsRefreshRequest) -> TransactionsRefreshResponse: ...
    def webhook_verification_key_get(self, request: WebhookVerificationKeyGetRequest) -> WebhookVerificationKeyGetResponse: ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
